openapi: "3.0.0"
info:
  version: 1.0.0
  title: Argos Service
  license:
    name: Apache License 2.0
servers:
  - url: http://localhost:8080/api
paths:
  /link/{supplyChainId}/query:
    get:
      summary: find link
      operationId: findLink
      tags:
        - link
      parameters:
        - name: supplyChainId
          in: path
          description: supply chain id
          required: true
          schema:
            type: string
        - name: hash
          in: query
          description: hash of product or material
          required: false
          schema:
            type: string
      responses:
        '200':
          description: array of links
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LinkMetaBlock"
        '400':
          description: validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /link/{supplyChainId}:
    post:
      summary: Create a link
      operationId: createLink
      tags:
        - link
      parameters:
        - name: supplyChainId
          in: path
          description: supply chain id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LinkMetaBlock"
      responses:
        '201':
          description: Null response
        '400':
          description: validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /key:
    post:
      summary: stores a public and private key pair
      operationId: storeKey
      tags:
        - key
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/KeyPair"
      responses:
        '201':
          description: Null response
        '400':
          description: validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /key/{keyId}:
    get:
      summary: get a key pair by id
      operationId: getKey
      tags:
        - key
      parameters:
        - name: keyId
          in: path
          description: key pair id
          required: true
          schema:
            type: string
            minLength: 64
            maxLength: 64
            pattern: '^[0-9a-f]*$'
      responses:
        '200':
          description: Key pair
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeyPair"
        '400':
          description: validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    LinkMetaBlock:
      type: object
      required:
        - signature
        - link
      properties:
        signature:
          $ref: "#/components/schemas/Signature"
        link:
          $ref: "#/components/schemas/Link"
    Signature:
      type: object
      required:
        - keyId
        - signature
      properties:
        keyId:
          type: string
          minLength: 64
          maxLength: 64
          pattern: '^[0-9a-f]*$'
        signature:
          type: string
          minLength: 512
          maxLength: 512
          pattern: '^[0-9a-f]*$'
    Link:
      type: object
      required:
        - stepName
      properties:
        command:
          type: array
          items:
            type: string
            pattern: '^[0-9a-f]*$'
        materials:
          type: array
          items:
            $ref: "#/components/schemas/Artifact"
        stepName:
          type: string
        products:
          items:
            $ref: "#/components/schemas/Artifact"
    Artifact:
      type: object
      required:
        - uri
        - hash
      properties:
        uri:
          type: string
          maxLength: 1024
          pattern: '^(\/?[\p{L}0-9. _-]+)+\/?$'
        hash:
          type: string
          minLength: 64
          maxLength: 64
          pattern: '^[0-9a-f]*$'
    KeyPair:
      type: object
      required:
        - keyId
        - publicKey
      properties:
        keyId:
          type: string
          minLength: 64
          maxLength: 64
          pattern: '^[0-9a-f]*$'
        publicKey:
          type: string
          format: byte
        encryptedPrivateKey:
          type: string
          format: byte
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string