---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3.6.2-ibmjava-alpine
    environment:
      JAVA_1_8_LOCATION: /usr/lib/jvm/java-1.8-openjdk
      JAVA_11_LOCATION: /usr/lib/jvm/java-11-openjdk
    commands:
      - apk --no-cache add openjdk11
      - apk --no-cache add openjdk8
      - export =
      - export =
      - mkdir ~/.m2
      - cp toolchains.xml.template ~/.m2/toolchains.xml
      - mvn -q package
      - ls -l argos-service/target

  - name: sonar
    image: maven:3.6.2-ibmjava-alpine
    environment:
      SONAR_LOGIN:
        from_secret: sonar_login
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=argos-scc_argos -Dsonar.organization=argos-scc -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$sonar_login

trigger:
  event:
    - push