---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: maven:3.6.2-ibmjava-alpine
    commands:
      - apk --no-cache add openjdk11
      - mvn -q package

trigger:
  event:
    - push