---
kind: pipeline
name: argosbuild
type: docker

steps:
  - name: build
    image: rabobanknl/argos-build:latest
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - mvn -q install

  - name: sonar
    image: rabobanknl/argos-build:latest
    environment:
      SONAR_LOGIN:
        from_secret: sonar_login
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - mvn -q -e verify sonar:sonar -Psonar -Dsonar.projectKey=rabobank_argos -Dsonar.organization=rabobank -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
    depends_on: 
      - build

  - name: pitest
    image: rabobanknl/argos-build:latest
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - mvn -q -e verify -Ppitest
    depends_on: 
      - sonar

  - name: build argos service image
    image: plugins/docker
    settings:
      repo: rabobanknl/argos-service
      tags: ${DRONE_COMMIT:0:8}
      context: argos-docker
      dockerfile: argos-docker/ServiceDockerfile
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    depends_on: 
      - pitest
      - sonar
  - name: build argos jenkins image
    image: plugins/docker
    settings:
      repo: rabobanknl/argos-jenkins
      tags: ${DRONE_COMMIT:0:8}
      context: argos-docker
      dockerfile: argos-docker/JenkinsDockerfile
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    depends_on: 
      - pitest
      - sonar

  - name: mongodb
    image: mongo:4.2.1-bionic
    detach: true
    depends_on: 
      - pitest
      - sonar
  - name: argos-service
    image: rabobanknl/argos-service:${DRONE_COMMIT:0:8}
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/test
      spring.profiles.active: default,integration-test
    detach: true
    depends_on: 
      - mongodb
      - build argos service image
    
  - name: argos-jenkins
    image: rabobanknl/argos-jenkins:${DRONE_COMMIT:0:8}
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    detach: true
    depends_on:
      - build argos jenkins image

  - name: regression test
    image: rabobanknl/argos-build:latest
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - mvn -q clean install -Dmaven.test.skip=true
      - cd argos-test
      - mvn -q clean verify -Pregression-test-drone
    depends_on: 
      - argos-jenkins
      - argos-service

volumes:
  - name: mvn_cache
    temp: {}

trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
name: build build image

steps:
  - name: build build image
    image: plugins/docker
    settings:
      repo: rabobanknl/argos-build
      tags: latest
      context: docker-build-image
      dockerfile: docker-build-image/Dockerfile
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token

trigger:
  ref:
    include:
      - refs/tags/build-image**