---
kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: rabobanknl/argos-build:latest
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - mvn -q install
      - ls -l argos-service/target
#
#  - name: sonar
#    image: rabobanknl/argos-build:latest
#    environment:
#      SONAR_LOGIN:
#        from_secret: sonar_login
#    volumes:
#      - name: mvn_cache
#        path: /root/.m2/repository
#    commands:
#      - mvn -q -e verify sonar:sonar -Psonar -Dsonar.projectKey=rabobank_argos -Dsonar.organization=rabobank -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
#
#  - name: pitest
#    image: rabobanknl/argos-build:latest
#    volumes:
#      - name: mvn_cache
#        path: /root/.m2/repository
#    commands:
#      - mvn -q -e verify -Ppitest
#
#  - name: build argos service image
#    image: plugins/docker
#    settings:
#      repo: rabobanknl/argos-service
#      tags: latest
#      context: argos-docker
#      dockerfile: argos-docker/ServiceDockerfile
#      username:
#        from_secret: docker_login_user
#      password:
#        from_secret: docker_login_token


  - name: argos-service
    image: rabobanknl/argos-build:latest
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/test
    detach: true
    command: "java -jar /argos-service.jar"

  - name: test
    image: rabobanknl/argos-build:latest
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - cd argos-test
      - mvn -q -e verify -Pregression-test-drone
services:
  - name: mongo
    image: mongo:4.2.0-bionic
volumes:
  - name: mvn_cache
    temp: {}
trigger:
  event:
    - push

---
kind: pipeline
name: build build image

steps:
  - name: build build image
    image: plugins/docker
    settings:
      repo: rabobanknl/argos-build
      tags: latest
      context: docker-build-image
      dockerfile: docker-build-image/Dockerfile
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token

trigger:
  ref:
    include:
      - refs/tags/build-image**