---
kind: pipeline
type: docker
name: argosbuild

platform:
  os: linux
  arch: amd64
  
steps:
- name: pre-argos
  image: argosnotary/argos4j-cli:1.0.1
  commands:
  - argos-cli --config-file argos-settings.json postLink --phase PRE -b /drone/src -p /drone/src --segment drone --step build -q ${DRONE_TAG} --runId ${DRONE_TAG}
  environment:  
    WORKSPACE: /home/argos
    CREDENTIALS_PASSPHRASE:
      from_secret: drone_sa_password
    CREDENTIALS_KEY_ID:
      from_secret: drone_sa_keyid
  volumes:
  - name: argos_workspace
    path: /home/argos
  when:
    event:
    - tag

- name: build
  image: argosnotary/argos-build:3.6.3-docker
  commands:
  - mvn versions:set -DnewVersion=${DRONE_TAG:-${DRONE_BRANCH//\//_}} -DgenerateBackupPoms=false -DprocessAllModules
  - mvn install jacoco:report sonar:sonar -Psonar -Dsonar.projectKey=argosnotary_argos-parent -Dsonar.organization=argosnotary -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
  environment:
    SONAR_LOGIN:
      from_secret: sonar_login
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  depends_on:
  - pre-argos
  
- name: post-argos
  image: argosnotary/argos4j-cli:1.0.1
  commands:
  - argos-cli --config-file argos-settings.json postLink --phase POST -b /drone/src -p /drone/src --segment drone --step build -q ${DRONE_TAG} --runId ${DRONE_TAG}
  environment:  
    WORKSPACE: /home/argos
    CREDENTIALS_PASSPHRASE:
      from_secret: drone_sa_password
    CREDENTIALS_KEY_ID:
      from_secret: drone_sa_keyid
  volumes:
  - name: argos_workspace
    path: /home/argos
  when:
    event:
    - tag
  depends_on:
  - build

- name: build images
  image: argosnotary/argos-build:3.6.3-docker
  commands:
  - docker build --tag argosnotary/argos-service:${DRONE_TAG:-${DRONE_BRANCH//\//_}} --build-arg VERSION=${DRONE_TAG:-${DRONE_BRANCH//\//_}} -f argos-docker/ServiceDockerfile argos-docker
  - docker build --tag argosnotary/argos-integration-test-service:latest -f argos-docker/IntegrationTestServiceDockerfile argos-docker
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  depends_on:
  - build
  - post-argos

- name: mongodb
  image: argosnotary/mongo:4.2.8
  detach: true
  depends_on:
  - build images

- name: argos-integration-test-stub
  image: argosnotary/oauth-stub:2.25.1
  detach: true
  depends_on:
  - build images
    
- name: argos-service
  image: argosnotary/argos-service:${DRONE_TAG:-${DRONE_BRANCH//\//_}}
  pull: never
  detach: true
  environment:
    auth.frontendRedirectBasePath: http://argos-integration-test-stub:8080
    jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
    spring.data.mongodb.uri: mongodb://mongodb/argos
    spring.data.mongodb.database: argos
    spring.security.oauth2.client.provider.azure.authorizationUri: http://argos-integration-test-stub:8080/oauth2/v2.0/authorize
    spring.security.oauth2.client.provider.azure.tokenUri: http://argos-integration-test-stub:8080/oauth2/v2.0/token
    spring.security.oauth2.client.provider.azure.userInfoUri: http://argos-integration-test-stub:8080/v1.0/me
    spring.security.oauth2.client.registration.azure.clientId: client-id
    spring.security.oauth2.client.registration.azure.clientSecret: client-secret
    spring.profiles.active: integration-test
  depends_on:
  - build images
  - mongodb
  - argos-integration-test-stub
  
- name: argos-integration-test-service
  image: argosnotary/argos-integration-test-service:latest
  pull: never
  detach: true
  environment:
    spring.data.mongodb.uri: mongodb://mongodb/argos
    spring.data.mongodb.database: argos
  depends_on:
  - build images
  - mongodb
  - argos-integration-test-stub
  
- name: argos-jenkins
  image: argosnotary/argos-jenkins-base:latest
  pull: always
  detach: true
  environment:
    JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    argosServiceUrl: http://argos-service:8080
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  depends_on:
  - build images
  - post-argos
  
- name: regression test
  image: argosnotary/argos-build:3.6.3-docker
  commands:
  - cd argos-test
  - mvn -q clean verify -Pregression-test-drone
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  depends_on:
  - argos-jenkins
  - argos-service
  - argos-integration-test-service
  - mongodb
  - post-argos

- name: argos-release-check
  image: argosnotary/argos4j-cli:1.0.1
  commands:
  - argos-cli --config-file argos-settings.json release
  environment:  
    CREDENTIALS_PASSPHRASE:
      from_secret: drone_sa_password
    CREDENTIALS_KEY_ID:
      from_secret: drone_sa_keyid
  volumes:
  - name: argos_workspace
    path: /home/argos/workspace
  when:
    event:
    - tag
  depends_on:
  - regression test

- name: release argos service image
  image: argosnotary/argos-build:3.6.3-docker
  commands:
  - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
  - docker push argosnotary/argos-service:${DRONE_TAG:-${DRONE_BRANCH//\//_}}
  environment:  
    DOCKER_USERNAME:
      from_secret: docker_username  
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/*"
    event:
    - push
    - tag
  depends_on:
  - regression test
  - argos-release-check

- name: sign artifacts
  image: plugins/gpgsign
  settings:
    detach_sign: true
    files:
    - argos4j/target/*.jar
    - argos4j/dependency-reduced-pom.xml
    - argos-service/target/*.jar
    - argos-service/pom.xml
    key:
      from_secret: argos-signing-private-key
    passphrase:
      from_secret: argos-signing-private-key-passphrase
  when:
    event:
    - tag
  depends_on:
  - argos-release-check

- name: deploy release to sonatype
  image: argosnotary/argos-build:3.6.3-docker
  commands:
  - cp argos4j/dependency-reduced-pom.xml argos4j/pom.xml
  - cp argos4j/dependency-reduced-pom.xml.asc argos4j/pom.xml.asc
  - mvn -f argos4j/pom.xml deploy:deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/
  - mvn -f argos-service/pom.xml deploy:deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2/
  environment:
    ossrh_password:
      from_secret: ossrh_login_password
    ossrh_username:
      from_secret: ossrh_login_user
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  when:
    event:
    - tag
  depends_on:
  - sign artifacts
  
- name: slack on success
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  depends_on:
  - release argos service image
  - deploy release to sonatype
  - regression test
  
volumes:
- name: mvn_cache
  host:
    path: /datadisk/mvn
- name: docker_socket
  host:
    path: /var/run/docker.sock
- name: argos_workspace
  temp: {}

trigger:
  event:
  - push
  - tag
  - pull_request

---
kind: pipeline
type: docker
name: report result

platform:
  os: linux
  arch: amd64

steps:
- name: slack on failure
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook

trigger:
  status:
  - failure
  event:
  - push
  - tag
  - pull_request

depends_on:
- argosbuild

---
kind: signature
hmac: b089c7f4e6b4f52e56dd16f51da61ddfbf768debda7651e37daf1d39a6d078c4

...
