---
kind: pipeline
name: argosbuild
type: docker

steps:
  - name: build
    image: rabobanknl/argos-build:repro
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    environment:
      GITHUB_USER:
        from_secret: github_user
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - mvn -q install
      - cd argos4j
      - mvn deploy

  - name: sonar
    image: rabobanknl/argos-build:latest
    environment:
      SONAR_LOGIN:
        from_secret: sonar_login
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - mvn -q -e verify sonar:sonar -Psonar -Dsonar.projectKey=rabobank_argos -Dsonar.organization=rabobank -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN

  - name: pitest
    image: rabobanknl/argos-build:latest
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - mvn -q -e verify -Ppitest

  - name: build argos service image
    image: plugins/docker
    settings:
      repo: rabobanknl/argos-service
      tags: latest
      context: argos-docker
      dockerfile: argos-docker/ServiceDockerfile
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
  - name: build argos jenkins image
    image: plugins/docker
    settings:
      repo: rabobanknl/argos-jenkins
      tags: latest
      context: argos-docker
      dockerfile: argos-docker/JenkinsDockerfile
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token

volumes:
  - name: mvn_cache
    temp: {}
trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
name: regression test
type: docker

services:
  - name: mongodb
    image: mongo:4.2.1-bionic
  - name: argos-service
    image: rabobanknl/argos-service:latest
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/test
      spring.profiles.active: default,integration-test
  - name: argos-jenkins
    image: rabobanknl/argos-jenkins:latest
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
#  - name: sonarqube
#    image: sonarqube

steps:
  - name: regression test
    image: rabobanknl/argos-build:latest
    volumes:
      - name: mvn_cache
        path: /root/.m2/repository
    commands:
      - mvn -q clean install -Dmaven.test.skip=true
      - cd argos-test
      - mvn -q clean verify -Pregression-test-drone

volumes:
  - name: mvn_cache
    temp: {}

depends_on:
  - argosbuild

trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
name: build build image

steps:
  - name: build build image
    image: plugins/docker
    settings:
      repo: rabobanknl/argos-build
      tags: latest
      context: docker-build-image
      dockerfile: docker-build-image/Dockerfile
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token

trigger:
  ref:
    event:
      - push
    include:
      - refs/tags/build-image**