#
# Copyright (C) 2019 - 2020 Rabobank Nederland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# For caching maven artifacts create first a docker volume with the command:
#
# docker volume create --name=maven_cache
#

version: '3.1'

services:

  argos-service:
    build:
      context: .
      dockerfile: ServiceDockerfile
      args:
        - VERSION=compose
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/test
      spring.security.oauth2.client.registration.azure.clientId: client-id
      spring.security.oauth2.client.registration.azure.clientSecret: client-secret
      spring.security.oauth2.client.provider.azure.authorizationUri: http://localhost:8087/oauth2/v2.0/authorize-manual
      spring.security.oauth2.client.provider.azure.tokenUri: http://oauth-stub:8080/oauth2/v2.0/token
      spring.security.oauth2.client.provider.azure.userInfoUri: http://oauth-stub:8080/v1.0/me
      jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
      auth.frontendRedirectBasePath: http://localhost:3000
      spring.profiles.active: integration-test
      JAVA_OPTS: '-Xmx1g'
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  oauth-stub:
    image: argosnotary/argos-integration-test-stub:master
    ports:
      - 8087:8080

  argos-integration-test-service:
    build:
      context: .
      dockerfile: IntegrationTestServiceDockerfile
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/test
      jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
      JAVA_OPTS: '-Xmx500m'
    ports:
      - 2877:2877
    depends_on:
      - mongodb

  mongodb:
    build:
      context: mongo
    ports:
      - 27017:27017

  jenkins:
    build:
      context: .
      dockerfile: JenkinsDockerfile
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Xmx1g
      - snapshotsUrl=http://nexus:8081/nexus/content/repositories/snapshots/
      - releasesUrl=http://nexus:8081/nexus/content/repositories/releases/
    volumes:
      - maven_cache:/root/.m2/repository
    ports:
      - 9080:8080
    depends_on:
      - nexus
      - xldeploy

  xldeploy:
    build:
      context: .
      dockerfile: XLDeployDockerfile
    environment:
      ADMIN_PASSWORD: admin
      ACCEPT_EULA: Y
      JAVA_OPTS: '-Xmx1g'
    ports:
      - 4516:4516
      
  tomcat:
    image: argosnotary/xld-tomcat-target:9.0
    environment:
      JAVA_OPTS: '-Xmx500m'
    ports:
      - "8082:8080"
      - "2022:22"

  nexus:
    image: sonatype/nexus:2.14.15-01
    environment:
      JAVA_OPTS: '-Xmx500m'
    ports:
      - 8081:8081

volumes:
  maven_cache:
    external: true

