version: '3.1'

services:

  argos-service:
    build:
      context: .
      dockerfile: ServiceDockerfile
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/test
      spring.profiles.active: default,integration-test
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - 27017:27017
      
  jenkins:
    build:
      context: .
      dockerfile: JenkinsDockerfile
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - 9080:8080
    depends_on:
      - argos-service