#
# Argos Notary - A new way to secure the Software Supply Chain
#
# Copyright (C) 2019 - 2020 Rabobank Nederland
# Copyright (C) 2019 - 2021 Gerard Borst <gerard.borst@argosnotary.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

#
# For caching maven artifacts create first a docker volume with the command:
#
# docker volume create --name=maven_cache
#

version: '3.1'

services:

  argos-service:
    image: argosnotary/argos-docker-base:11.0.8
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/argos
      spring.data.mongodb.database: argos
      spring.security.oauth2.client.registration.azure.clientId: client-id
      spring.security.oauth2.client.registration.azure.clientSecret: client-secret
      spring.security.oauth2.client.provider.azure.authorizationUri: http://localhost:8087/oauth2/v2.0/authorize
      spring.security.oauth2.client.provider.azure.tokenUri: http://oauth-stub:8080/oauth2/v2.0/token
      spring.security.oauth2.client.provider.azure.userInfoUri: http://oauth-stub:8080/v1.0/me
      jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
      auth.frontendRedirectBasePath: http://localhost:8087
      spring.profiles.active: integration-test
      JAVA_OPTS: '-Xmx1g'
    ports:
      - 8080:8080
    volumes:
      - ../argos-service/target/argos-service.jar:/argos.jar
    depends_on:
      - mongodb

  oauth-stub:
    image: argosnotary/oauth-stub:2.25.1
    environment:
      JAVA_OPTS: '-Xmx500m'
    ports:
      - 8087:8080

  argos-integration-test-service:
    image: argosnotary/argos-docker-base:11.0.8
    environment:
      spring.data.mongodb.uri: mongodb://mongodb/argos
      spring.data.mongodb.database: argos
      jwt.token.secret: Z2LcVpgCuGtpb5rBDNIIWGe8RXqYGWDpWFjWhYQUS2Z8rjE2/GTJlu0s6BRYG0Mn0kV8StC9cFE83Jkl68RCkw==
      JAVA_OPTS: '-Xmx500m'
    ports:
      - 2877:2877
    volumes:
      - ../argos-integration-test-service/target/argos-integration-test-service.jar:/argos.jar
    depends_on:
      - mongodb

  mongodb:
    image: argosnotary/mongo:4.2.8
    ports:
      - 27017:27017

  jenkins:
    image: argosnotary/argos-jenkins-base:latest
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Xmx1g
      - argosServiceUrl=http://argos-service:8080
    volumes:
      - maven_cache:/root/.m2/repository
      - ../argos-jenkins-plugin/target/argos.hpi:/usr/share/jenkins/ref/plugins/argos.hpi
    ports:
      - 9080:8080

volumes:
  maven_cache:
    external: true

